from fpdf import FPDF
from pathlib import Path
import json

class PDFReporter(FPDF):
    def __init__(self, project_data, funnel_data, ai_analysis, lead_data=None):
        super().__init__()
        self.project = project_data
        self.funnel = funnel_data
        self.analysis = ai_analysis
        self.leads = lead_data or []
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Header on all pages except cover?
        # For simplicity, just small header
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f"Confidential Audit: {self.project.get('url')}", align='R')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

    def create_cover(self):
        self.add_page()
        self.set_fill_color(20, 20, 30) # Dark background
        self.rect(0, 0, 210, 297, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('helvetica', 'B', 24)
        self.ln(80)
        self.cell(0, 10, "FUNNEL HACKER AI", align='C')
        self.ln(20)
        
        self.set_font('helvetica', '', 16)
        self.cell(0, 10, "Strategic Competitor Audit", align='C')
        self.ln(10)
        self.set_font('helvetica', 'I', 12)
        self.cell(0, 10, f"Target: {self.project.get('url')}", align='C')
        self.ln(50)
        
        self.set_font('helvetica', '', 10)
        self.cell(0, 10, "Generated by Funnel Hacker AI (Enterprise)", align='C')

    def add_tech_stack_section(self):
        self.add_page()
        self.set_text_color(0, 0, 0)
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 10, "1. Tech Stack & Infrastructure", ln=True)
        self.ln(5)
        
        self.set_font('helvetica', '', 11)
        # Aggregate stats
        platforms = set()
        pixels = set()
        prices = set()
        
        for step in self.funnel:
            stack = step.get('tech_stack', {})
            if stack.get('platform') and stack.get('platform') != 'Custom/Unknown':
                platforms.add(stack.get('platform'))
            for p in stack.get('pixels', []):
                pixels.add(p)
            for pr in step.get('prices_detected', []):
                prices.add(pr)
                
        self.multi_cell(0, 7, f"Platforms Detected: {', '.join(platforms) if platforms else 'None detected'}")
        self.multi_cell(0, 7, f"Tracking Pixels: {', '.join(pixels) if pixels else 'None detected'}")
        self.multi_cell(0, 7, f"Pricing Found: {', '.join(prices) if prices else 'No pricing text found'}")
        self.ln(10)

    def add_funnel_map_section(self):
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 10, "2. Funnel Architecture Map", ln=True)
        self.ln(5)
        
        self.set_font('courier', '', 10)
        for step in self.funnel:
            title = (step.get('title') or "Untitled").strip()[:50]
            url_path = Path(step.get('url', '')).name or "/"
            line = f"[{step.get('step')}] {title} -> /{url_path}"
            self.cell(0, 6, line, ln=True)
        self.ln(10)

    def add_ai_analysis_section(self):
        self.add_page()
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 10, "3. AI Strategic Consultant", ln=True)
        self.ln(5)
        
        # Clean Markdown somewhat
        clean_text = self.analysis.replace("**", "").replace("#", "")
        
        self.set_font('helvetica', '', 11)
        self.multi_cell(0, 7, clean_text)

    def add_enrichment_section(self):
        if not self.leads:
            return
            
        self.add_page()
        self.set_font('helvetica', 'B', 16)
        self.cell(0, 10, "4. Lead Enrichment Data", ln=True)
        self.ln(5)
        
        self.set_font('helvetica', '', 10)
        self.multi_cell(0, 7, f"Total Leads Captured: {len(self.leads)}")
        self.ln(5)
        
        # Table Header
        self.set_font('helvetica', 'B', 9)
        self.cell(40, 7, "Name", 1)
        self.cell(50, 7, "Email", 1)
        self.cell(40, 7, "Industry", 1)
        self.cell(30, 7, "Quality Score", 1, ln=True)
        
        # Table Rows (Limit to 20 for PDF)
        self.set_font('helvetica', '', 8)
        for lead in self.leads[:20]:
            data = lead.get('data', {})
            enrichment = data.get('enrichment', {}).get('data', {})
            
            name = str(data.get('name', 'N/A'))[:20]
            email = str(data.get('email', 'N/A'))[:25]
            
            # Extract industry from insights if available
            industry = "N/A"
            insights = enrichment.get('business_insights', [])
            for i in insights:
                 if i.get('type') == 'industry':
                     industry = i.get('value', 'N/A')
                     break
            
            score = str(enrichment.get('score', 'N/A'))
            
            self.cell(40, 6, name, 1)
            self.cell(50, 6, email, 1)
            self.cell(40, 6, str(industry)[:20], 1)
            self.cell(30, 6, score, 1, ln=True)

    def generate(self, output_path: Path):
        self.create_cover()
        self.add_tech_stack_section()
        self.add_funnel_map_section()
        self.add_ai_analysis_section()
        self.add_enrichment_section()
        self.output(str(output_path))
