-- Run this in the Supabase SQL Editor

create table public.projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  mode text,
  status text,
  local_path text,
  error_msg text,
  funnel_data jsonb,
  ai_analysis text
);

-- Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- Create Policy to allow read/write access (For Dev/Public usage)
-- WARNING: In production, restrict this to authenticated users
create policy "Enable all access for anon" on public.projects
for all using (true) with check (true);
