import fastify from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import cors from '@fastify/cors';
import dotenv from 'dotenv';
import { userRoutes } from './routes/user.route';
import { funnelRoutes } from './routes/funnel.route';
import { leadRoutes } from './routes/lead.route';
import { automationRoutes } from './routes/automation.route';

dotenv.config();

const app = fastify({ logger: true });

// CORS para o frontend
app.register(cors, {
  origin: ['http://localhost:5173'], // ajuste se precisar
});

// Swagger/OpenAPI com bearerAuth
app.register(swagger, {
  openapi: {
    info: {
      title: 'StrateUp API',
      description: 'API documentation generated by Swagger',
      version: '1.0.0'
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT'
        }
      }
    }
  }
});
app.register(swaggerUi, {
  routePrefix: '/docs'
});

// Health check
app.get('/health', {
  schema: {
    description: 'Health check',
    tags: ['System'],
    summary: 'Checagem de saúde',
    response: {
      200: {
        type: 'object',
        properties: {
          status: { type: 'string' }
        }
      }
    }
  }
}, async () => ({ status: 'ok' }));

// Rotas protegidas
app.register(userRoutes);
app.register(funnelRoutes);
app.register(leadRoutes);
app.register(automationRoutes);

const start = async () => {
  try {
    await app.listen({ port: 3000, host: '0.0.0.0' });
    console.log('Server listening on http://localhost:3000');
  } catch (err) {
    app.log.error(err);
    process.exit(1);
  }
};

start();